### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by tailorvj** [jalbertsr/react-twitter-clone#1]
Hi, I've cloned, created a firebase project, changed the firebase config and ran npm install - it failed to install. 

Kind regards,
Tailor

**Comment by jalbertsr** [comment]
Hi tailorvj, can you specify what kind of error npm failed with? it will make it easier to help you. 

This small MVP project is 2 years old now and has very old npm dependencies, since some people have gained interest in it, I'm planning to do it again from scratch with new React version.

**Comment by tailorvj** [comment]
I'm sorry, but I can't recall the errors now. I guess it doesn't really matter though, as it happens on any machine, due to old npm modules. Please let me know when you update it. It looks like a nice educational project for React.

Cheers,
Tailor

**Comment by jalbertsr** [comment]
Hi, I updated all the main dependencies and I think it should work now.

If something is still now working for you, don't hesitate to reopen again the issue.

Thanks for reaching me out.
